import CarClass as c 

toyota=c.Car('12', 'toyota')
toyota.accelerate()
print(toyota.get_speed())
toyota.accelerate()
print(toyota.get_speed())
toyota.accelerate()
print(toyota.get_speed())
toyota.accelerate()
print(toyota.get_speed())
toyota.accelerate()
print(toyota.get_speed())

toyota.brake()
print(toyota.get_speed())
toyota.brake()
print(toyota.get_speed())
toyota.brake()
print(toyota.get_speed())
toyota.brake()
print(toyota.get_speed())
toyota.brake()
print(toyota.get_speed())

